# Generated by Django 5.0.2 on 2024-02-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
    ]
